version: "3.9"

services:
  web:
    build: .
    command: gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000  # Django —Å Gunicorn
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=habit_tracker.settings
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A habit_tracker.celery worker -l INFO  # Celery worker
    environment:
      - DJANGO_SETTINGS_MODULE=habit_tracker.settings
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data: