version: "3.12"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=habit_tracker.settings
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - .:/app  # Убрать для production
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A habit_tracker.celery worker -l INFO  # Добавлено: команда Celery
    environment:
      - DJANGO_SETTINGS_MODULE=habit_tracker.settings
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - .:/app  # Убрать для production
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"  # Для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
    depends_on:
      - web

volumes:
  postgres_data: