# Generated by Django 5.2 on 2025-07-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, где выполняется привычка.', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время выполнения привычки.', verbose_name='Время')),
                ('action', models.CharField(help_text='Описание действия, представляющего привычку.', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Укажите, является ли привычка приятной.', verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(default=1, help_text='Периодичность выполнения привычки (в днях, от 1 до 7).', verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение после выполнения привычки.', max_length=255, verbose_name='Вознаграждение')),
                ('execution_time', models.IntegerField(default=120, help_text='Время, необходимое для выполнения привычки (в секундах).', verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, help_text='Укажите, является ли привычка публичной.', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, связанная с выполнением этой привычки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(help_text='Пользователь, создавший привычку.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['time'],
            },
        ),
    ]
