# Generated by Django 5.2 on 2025-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.IntegerField(default=120, help_text='Время, необходимое для выполнения привычки (в секундах).', verbose_name='Время на выполнение (в секундах)'),
        ),
    ]
