# Generated by Django 5.2 on 2025-06-21 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['time'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='Описание действия, представляющего привычку.', max_length=255, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.IntegerField(help_text='Время, необходимое для выполнения привычки (в секундах).', verbose_name='Время на выполнение (в секундах)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, help_text='Укажите, является ли привычка приятной.', verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Укажите, является ли привычка публичной.', verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, help_text='Периодичность выполнения привычки (в днях, от 1 до 7).', verbose_name='Периодичность (в днях)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(help_text='Место, где выполняется привычка.', max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Приятная привычка, связанная с выполнением этой привычки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='Вознаграждение после выполнения привычки.', max_length=255, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(help_text='Время выполнения привычки.', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший привычку.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
