# Generated by Django 5.2 on 2025-07-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя Telegram')),
                ('tg_chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
