# Generated by Django 5.2 on 2025-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя Telegram'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
